name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/*
  pull_request:
    branches: 
      - main
  schedule:
   - cron: "15 6 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show Event Name
        run: echo "The event that triggered this workflow is: ${{ github.event }}"
      - name: Show Branch Name
        run: echo "${{ github.brach_name }}"
        
    
