name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/*
  pull_request:
    branches: 
      - main
  schedule:
   - cron: "15 6 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show Event Name
        run: echo "${{ toJSON(github.event_name) }}"
      - name: Show Branch Name
        run: echo "${{ github.ref }}"
      - name: Show repositoy
        run: echo "${{ github.repository }}"
    
